### ISSUE TITLE
create landing page for all the stories

### ISSUE THREAD

**Issue by bermud** [geosolutions-it/UNMISS-GeoStory#23]
UNMISS would like to have a landing page only for accessing their 10 GeoStories
This page should be structured as a grid template (as shown above in the picture), one button for each geostory. Clicking on a button should open the related geostory
If possible, the grid template should be embedded in the home page, otherwise in a specific page, to be accessed by clicking a Geostory button

**Comment by giohappy** [comment]
@EddyCatt I guess we can use this issue for the landing page. 
Please update the description from Luis with the most recent info and, in case, links to docs?

**Comment by EddyCatt** [comment]
UNMISS would like to have a landing page specifically for their 10 GeoStories, structured as a grid template (as shown above in the picture), one button for each geostory. Clicking on a button should open the related geostory
If possible, the grid template should be embedded in the home page, otherwise in a specific page accessed by clicking a Geostory button

**Comment by giohappy** [comment]
@DavidQuartz we should implement the simplest solution, even basic jquery + django template.
The filtered resources (/api/v2/resources?filter{resource_type.in}=geostory) will show up in a grid, similar to the one in master although without the three dots menu and the owner. Just the title, abstract and link to open it (without preview).

The grid will replace the area highlighted in the image below:

![image](https://user-images.githubusercontent.com/571129/175985964-e1b1bd95-9554-4fce-a409-de4863b146d4.png)

**Comment by EddyCatt** [comment]
It seems that using Microsoft Edge, Geostories are not in grid but only vertically aligned 
![image](https://user-images.githubusercontent.com/86973955/178446465-143b138e-257f-421f-8965-ac942699e8f2.png)

**Comment by giohappy** [comment]
it's the cache. The css url should be updated and forced the cleanup of the cache. I don't know why it didn't work here, maybe a stale CSS URL. We could investigate but I don't think it's worth a new change and upgrade, what do you think @EddyCatt ?

**Comment by giohappy** [comment]
The above comment from @EddyCatt is related to https://github.com/geosolutions-it/UNMISS-GeoStory/issues/48
For your convenience I copy the screenshot of the final design here below:

**Comment by DavidQuartz** [comment]
@giohappy I can push fixes for 1 2 5 and 6. Estimation is 2 (by close of day today)
Can you clarify which text is underlined ? @EddyCatt

**Comment by EddyCatt** [comment]
UNITED NATIONS (in UNITED NATIONS MISSION IN SOUTH SUDAN)

**Comment by marthamareal** [comment]
@giohappy I have tested the usage of HTML in the slide text and yes it is possible to use it. however, if you add the HTML for the button, the representation is text, not a button.

Also, we will need to make some amends to the current slide appearance in order to achieve having the content at the bottom(will have the view button) and name(will be the title of GeoStory) at the top. and also think of how to solve the issue above.

**Comment by giohappy** [comment]
>@giohappy I have tested the usage of HTML in the slide text and yes it is possible to use it. however, if you add the HTML for the button, the representation is text, not a button.

@marthamareal what do you mean by text? Is it going to show the HTML tags?
Anyway, I wouldn't bother. We can tell them that they can put an <a> element with the href to the story and, if they want, tha target blank. I guess this works fine, right?

**Comment by marthamareal** [comment]
It does not show the tags. just text. eg `<a href="/maps" class="btn btn-primary pull-right">View</a>` will show
![ss](https://user-images.githubusercontent.com/20810749/192724435-39b30996-065b-4da7-83ac-a21a1448c1f5.png)

**Comment by giohappy** [comment]
that's fine @marthamareal 

@EddyCatt for point 2 and 3 you will tell them that they will have to create the slides by themselves and that they can use HTML inside the slide content if they want to include a link to the geostory

![image](https://user-images.githubusercontent.com/571129/192742235-66984b2d-73b5-4769-b2cf-fdaf9d01d7af.png)

**Comment by DavidQuartz** [comment]
@EddyCatt How does this look? 
![responsive](https://user-images.githubusercontent.com/42542676/192774838-ce9e9e54-9aaf-4f2c-aae3-5e25e8bf3ca1.gif)


PS: Ignore any changes in logos or theme settings, those are only on my instance.

**Comment by EddyCatt** [comment]
it look pretty fine !
