### ISSUE TITLE
Create a template for new stories

### ISSUE THREAD

**Issue by bermud** [geosolutions-it/UNMISS-GeoStory#24]
Based on one of the current stories create a template to create the other stories

**Comment by ElenaGallo** [comment]
[Here](https://docs.google.com/document/d/1PScNkN0rMRt9jMKzxdJ2YUtX91iQ3XlXUUzyjTMKg80/edit?usp=sharing) the documentation to set a template and an example of [geostory template](https://stable.demo.geonode.org/apps/preview/3417)

**Comment by hosein021555** [comment]
I try to download the documentation but needs permission to access it, could you please share it via email in the Teams Channel.
