### ISSUE TITLE
Add basemap

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/UNMISS-GeoStory#26]
Add these basemap: […. \\user2\js\ol3-wfs-t.js](https://teams.microsoft.com/_#/zip/viewer/teams/https:~2F~2Funitednations.sharepoint.com~2Fsites~2FUNMISSStoryMap-GeoSolutions~2FShared%20Documents~2FGeneral~2FOpenlayers%20smaple.zip?threadId=19:JF_nT9xg5b2wmCg8hTsCjUrYk4NTytepZgMBlKDpDPs1@thread.tacv2&messageId=1632476217188&baseUrl=https:~2F~2Funitednations.sharepoint.com~2Fsites~2FUNMISSStoryMap-GeoSolutions&fileId=56c5f635-ce62-4780-84e8-b535b18b76b3&ctx=chiclet&viewerAction=view)

**Comment by hosein021555** [comment]
put more base maps in the story map 


Visit the web page below
https://esri.github.io/esri-leaflet/examples/switching-basemaps.html


It is highly recommended to put the Base maps listed below. 
'ArcGIS:Imagery',
    'ArcGIS:Imagery:Standard',
    'ArcGIS:Imagery:Labels',
    'ArcGIS:LightGray',
    'ArcGIS:LightGray:Base',
    'ArcGIS:LightGray:Labels',
    'ArcGIS:DarkGray',
    'ArcGIS:DarkGray:Base',
    'ArcGIS:DarkGray:Labels',
    'ArcGIS:Navigation',
    'ArcGIS:NavigationNight',
    'ArcGIS:Streets',
    'ArcGIS:StreetsNight',
    'ArcGIS:StreetsRelief',
    'ArcGIS:StreetsRelief:Base',
    'ArcGIS:Topographic',
    'ArcGIS:Topographic:Base',
    'ArcGIS:Oceans',
    'ArcGIS:Oceans:Base',
    'ArcGIS:Oceans:Labels',
    'OSM:Standard',
    'OSM:StandardRelief',
    'OSM:StandardRelief:Base',
    'OSM:Streets',
    'OSM:StreetsRelief',
    'OSM:StreetsRelief:Base',
    'OSM:LightGray',
    'OSM:LightGray:Base',
    'OSM:LightGray:Labels',
    'OSM:DarkGray',
    'OSM-DarkGray:Base',
    'OSM-DarkGray:Labels',
    'ArcGIS:Terrain',
    'ArcGIS:Terrain:Base',
    'ArcGIS:Terrain:Detail',
    'ArcGIS:Community',
    'ArcGIS:ChartedTerritory',
    'ArcGIS:ChartedTerritory:Base',
    'ArcGIS:ColoredPencil',
    'ArcGIS:Nova',
    'ArcGIS:ModernAntique',
    'ArcGIS:ModernAntique:Base',
    'ArcGIS:Midcentury',
    'ArcGIS:Newspaper',
    'ArcGIS:Hillshade:Light',
    'ArcGIS:Hillshade:Dark'

**Comment by ElenaGallo** [comment]
@hosein021555 basemap can be added as WMTS/CSW/WMS, no geojson. Thank you
