### ISSUE TITLE
Provide accessibility to MapStore for Hosein, Elvis and Bernard to could be able to design dashboards 

### ISSUE THREAD

**Issue by hosein021555** [geosolutions-it/UNMISS-GeoStory#27]
To design dashboards in the Storymaps, Please provide accessibility to the MapStore application for Hosein Mohammadi, Elvis Odhiambo AYIEMBA, and Benard Sabwa Akenga.

**Comment by ElenaGallo** [comment]
@hosein021555  dashboards will soon be available on GeoNode. Please wait a few days, thank you.
