### ISSUE TITLE
There is an issue with Save for Storymap 

### ISSUE THREAD

**Issue by hosein021555** [geosolutions-it/UNMISS-GeoStory#28]
When the other users except the owner have modifications on the Storymap he/she could not be able to save apps. 
for example, I can edit the apps that I am not the owner and I have to do a "save as" application to save the app.

**Comment by ElenaGallo** [comment]
@hosein021555 thank you. Open an issue for fix that (https://github.com/geosolutions-it/geonode/issues/985)
