### ISSUE TITLE
UNMISS basemap

### ISSUE THREAD

**Issue by ElenaGallo** [geosolutions-it/UNMISS-GeoStory#31]
Use the map present on the follow WMTS service as a basemap on GeoNode

> https://pro-ags1.dfs.un.org/arcgis/rest/services/ClearMap_WebPlain/MapServer/WMTS/1.0.0/WMTSCapabilities.xml

**Comment by simboss** [comment]
it shall be supported.

**Comment by ElenaGallo** [comment]
@giohappy what types of basemaps support geonode?

**Comment by giohappy** [comment]
@bermud do they want to use a specific WMTS layer? In that case it might be useful to have the URL of the service, if publicly accessible. From the service we might check it's CRS and, possibly, the gridset / tilematrix of the layer. @allyoucanmap correct me if I'm wrong, if we have this information we might configure a dedicated basemap.

**Comment by ElenaGallo** [comment]
@giohappy do we know more about this issue?

**Comment by giohappy** [comment]
@ElenaGallo I submitted some questions in my previous comment. I don't know who is following this client now. @simboss?

**Comment by ElenaGallo** [comment]
@giohappy they want to use the only WMTS layer present on the service attached to the issue (https://pro-ags1.dfs.un.org/arcgis/rest/services/ClearMap_WebPlain/MapServer/WMTS/1.0.0/WMTSCapabilities.xml).

**Comment by giohappy** [comment]
@ElenaGallo I'm investigating. Meanwhile I've tested that MapStore can use that WMTS layer: https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/37125
