### ISSUE TITLE
Modifications on Landing Page

### ISSUE THREAD

**Issue by EddyCatt** [geosolutions-it/UNMISS-GeoStory#48]
UNMISS is asking to apply some changes on the Landing Page and description in the About Page. See attached files
[Landing Page Change Recommendations.docx](https://github.com/geosolutions-it/UNMISS-GeoStory/files/9240001/Landing.Page.Change.Recommendations.docx)
[UNMISS Geostories About Page.docx](https://github.com/geosolutions-it/UNMISS-GeoStory/files/9240002/UNMISS.Geostories.About.Page.docx)

**Comment by EddyCatt** [comment]
In attachment, approved final version of the layout for the Landing Page. It substitutes the other recommendations. 
[Geostories Landing Page.pptx](https://github.com/geosolutions-it/UNMISS-GeoStory/files/9266649/Geostories.Landing.Page.pptx)

**Comment by giohappy** [comment]
@marthamareal most of the things requested in the two docs can be done either through the Django Admin theme (see notes below) or tweaking the custom home template.
You can ask @DavidQuartz a hand if needed, he created the custom home.

**Setup:**
1. use the master branch from this repo
2. load the [unmiss_themes](https://github.com/geosolutions-it/UNMISS-GeoStory/blob/master/src/fixtures/unmiss_themes.json) fixture manually
3. Edit the unmiss theme (Django admin) and set the following images:
   - logo: ![logo](https://user-images.githubusercontent.com/571129/183057660-ab938a33-8427-4581-a791-1d3d53ee21eb.png)
   - jumbotron image:  ![unmiss-jumbotron_1sNtCcg](https://user-images.githubusercontent.com/571129/183057763-7bb13342-1d6a-4467-a8a5-3db5d8407538.png)

**Comment by EddyCatt** [comment]
In the Landing Page, GeoNode menus must not be visible, only Sign-In, to login to access to the platform as administrator. Geostories have to be publicly accessible

**Comment by giohappy** [comment]
@EddyCatt deployed with a couple of example slides

![image](https://user-images.githubusercontent.com/571129/186375885-7df5ac23-a666-4fb2-b80a-118752e4b74e.png)

**Comment by EddyCatt** [comment]
IN the attached doc, the latest comments from UN about Landing Page, with minor modifications to be carried out

[UNMISS Geostories Landing Page Comments.docx](https://github.com/geosolutions-it/UNMISS-GeoStory/files/9800925/UNMISS.Geostories.Landing.Page.Comments.docx)

**Comment by giohappy** [comment]
@DavidQuartz please move forward with the requested adjustments.
Regarding poin t (carusel timing) I guess it's due to the image loading time.

**Comment by giohappy** [comment]
@EddyCatt new modifications deployed

![image (6)](https://user-images.githubusercontent.com/571129/200869447-e51600e3-91e8-4d4e-af71-e83e550698d2.png)
